// Generated by CoffeeScript 1.4.0
var GitAction, colors, onError, onNotify, onSuccess, program;

program = require('commander');

colors = require('colors');

GitAction = require('./git_action');

program.option('    --package-manager [package_manager]', 'Calls package manager after each clone/pull (default npm)');

program.option('-m, --message         [commit_message]', 'Specify commit message');

program.option('-d, --as-daemon       [config_file]', '[NOT YET IMPLEMENTED] Run as a daemon.');

program.option('-p, --as-proxy        [config_file]', '[NOT YET IMPLEMENTED] Run as a distribution proxy.');

try {
  onNotify = require('my_notifiers').gitSeed.onNotify;
  onError = require('my_notifiers').gitSeed.onError;
  onSuccess = require('my_notifiers').gitSeed.onSuccess;
} catch (error) {
  onSuccess = function(result) {};
  onError = function(reason) {};
  onNotify = function(status) {
    if (status.cli.context === 'good') {
      return console.log(("(" + status.cli.event + ")").bold.green, status.cli.detail);
    } else if (status.cli.context === 'bad') {
      return console.log(("(" + status.cli.event + ")").bold.red, status.cli.detail);
    } else {
      return console.log(("(" + status.cli.event + ")").bold, status.cli.detail);
    }
  };
}

program.command('init').description('Assemble the initial .nez_tree control file into [root]').action(function() {
  return GitAction.configure(program, onSuccess, onError, onNotify).init(arguments);
});

program.command('status').description('Git status across all nested git repos').action(function() {
  return GitAction.configure(program, onSuccess, onError, onNotify).status(arguments);
});

program.command('clone').description('Git clone all missing nested git repos').action(function() {
  return GitAction.assign(program).clone(arguments);
});

program.command('commit').description('Git commit across all nested repos with staged changes.').action(function() {
  return GitAction.configure(program, onSuccess, onError, onNotify).commit(arguments);
});

program.command('pull').description('Git pull across all nested git repos.').action(function() {
  return GitAction.configure(program, onSuccess, onError, onNotify).pull(arguments);
});

program.command('push').description('[PENDING] Git push across all nested git repos (per .git-seed)').action(function() {
  return GitAction.configure(program, onSuccess, onError, onNotify).push(arguments);
});

program.command('watch').description('[PENDING (maybe)] Attach console to github rss feeds for all nested repos').action(function() {});

program.parse(process.argv);

if (GitAction.error) {
  GitAction.showError();
  process.exit(1);
}
