// Generated by CoffeeScript 1.4.0
var GitRepo, GitTree, colors, fs;

fs = require('fs');

colors = require('colors');

GitRepo = require('./git_repo');

GitTree = (function() {

  GitTree.init = function(root, array) {
    var path, repoArray, _i, _len;
    repoArray = [];
    for (_i = 0, _len = array.length; _i < _len; _i++) {
      path = array[_i];
      repoArray.push(GitRepo.init(path));
    }
    return new GitTree(root, repoArray);
  };

  function GitTree(root, list) {
    this.root = root;
    this.control = "" + this.root + "/.git_tree";
    if (list instanceof Array) {
      this.array = list;
    } else if (typeof list === 'undefined') {
      this.array = this.load();
    }
  }

  GitTree.prototype.save = function() {
    try {
      return fs.writeFileSync("" + this.root + "/.git_tree", JSON.stringify(this.array, null, 2));
    } catch (error) {
      console.log(error.red);
      throw error;
    }
  };

  GitTree.prototype.load = function() {
    var array, json, properties, _i, _len;
    try {
      if (!fs.lstatSync(this.control).isFile()) {
        this.noControl();
      }
    } catch (error) {
      this.noControl(error);
    }
    try {
      json = JSON.parse(fs.readFileSync(this.control));
      array = [];
      for (_i = 0, _len = json.length; _i < _len; _i++) {
        properties = json[_i];
        array.push(new GitRepo(properties));
      }
      return array;
    } catch (error) {
      return this.noControl(error);
    }
  };

  GitTree.prototype.noControl = function(ex) {
    var error;
    throw error = ex || new Error('Expected control file, not this:' + this.control);
  };

  return GitTree;

})();

module.exports = GitTree;
