// Generated by CoffeeScript 1.4.0
var gitTools;

module.exports = gitTools = {
  showOrigin: function(workDir) {
    return 'get origin for' + workDir;
  },
  showBranch: function(workDir) {
    return 'get branch for' + workDir;
  },
  showRef: function(workDir) {
    return 'get ref for' + workDir;
  }
};
