// Generated by CoffeeScript 1.4.0
var GitAction, GitRepos;

GitRepos = require('./git_repos');

module.exports = GitAction = {
  isError: function() {
    return error === '';
  },
  showError: function() {
    return console.log(GitAction.error);
  },
  error: 'unknown or missing command',
  assign: function(program) {
    GitAction.root = program.root || '.';
    GitAction.message = program.message;
    return GitAction;
  },
  init: function() {
    var array, find, list;
    GitAction.error = '';
    list = {};
    array = [];
    find = require('findit').find(GitAction.root);
    find.on('end', function() {
      return GitRepos.init(array, GitAction.root);
    });
    return find.on('directory', function(dir, stat) {
      var match;
      if (match = dir.match(/(.*)\/.git\//)) {
        if (typeof list[match[1]] !== 'undefined') {
          return;
        }
        list[match[1]] = 1;
        return array.push(match[1]);
      }
    });
  },
  status: function() {
    return GitAction.error = '';
  },
  commit: function() {
    GitAction.error = '';
    return console.log('commit with', GitAction.message);
  },
  push: function() {
    return GitAction.error = '';
  },
  pull: function() {
    return GitAction.error = '';
  }
};
