// Generated by CoffeeScript 1.4.0
var GitRepo, GitTools;

GitTools = require('./git_tools');

GitRepo = (function() {

  GitRepo.init = function(workDir) {
    return new GitRepo({
      path: workDir,
      origin: GitTools.showOrigin(workDir),
      branch: GitTools.showBranch(workDir),
      ref: GitTools.showRef(workDir)
    });
  };

  function GitRepo(properties) {
    console.log('\ninit GitRepo @ \n', properties);
  }

  return GitRepo;

})();

module.exports = GitRepo;
