// Generated by CoffeeScript 1.4.0
var Git, GitRepo;

Git = require('./tools/git');

GitRepo = (function() {

  GitRepo.init = function(workDir) {
    return new GitRepo({
      path: workDir,
      origin: Git.showOrigin(workDir),
      branch: Git.showBranch(workDir),
      ref: Git.showRef(workDir)
    });
  };

  function GitRepo(properties) {
    var property;
    for (property in properties) {
      this[property] = properties[property];
    }
  }

  return GitRepo;

})();

module.exports = GitRepo;
