// Generated by CoffeeScript 1.4.0
var GitRepo, GitRepos;

GitRepo = require('./git_repo');

GitRepos = (function() {

  GitRepos.init = function(array, root) {
    var path, repo, _i, _len, _results;
    _results = [];
    for (_i = 0, _len = array.length; _i < _len; _i++) {
      path = array[_i];
      _results.push(repo = GitRepo.init(path));
    }
    return _results;
  };

  function GitRepos(controlFile) {}

  return GitRepos;

})();

module.exports = GitRepos;
