// Generated by CoffeeScript 1.4.0
var Shell, colors, git, waterfall;

Shell = require('./shell');

colors = require('colors');

waterfall = require('async').waterfall;

module.exports = git = {
  showOrigin: function(workDir) {
    var gitDir;
    gitDir = git.gitDir(workDir);
    try {
      return Shell.execSync("git --git-dir=" + gitDir + " config --get remote.origin.url");
    } catch (error) {
      console.log(error.red);
      throw error;
    }
  },
  showBranch: function(workDir) {
    var gitDir;
    gitDir = git.gitDir(workDir);
    try {
      return Shell.execSync("cat " + gitDir + "/HEAD").match(/ref: (.*)$/)[1];
    } catch (error) {
      console.log(error.red);
      throw error;
    }
  },
  showRef: function(workDir) {
    var branch, gitDir;
    gitDir = git.gitDir(workDir);
    branch = git.showBranch(workDir);
    try {
      return Shell.execSync("cat " + gitDir + "/" + branch);
    } catch (error) {
      console.log(error.red);
      throw error;
    }
  },
  showStatus: function(workDir) {
    var gitDir;
    gitDir = git.gitDir(workDir);
    try {
      return Shell.execSync("git --git-dir=" + gitDir + " --work-tree=" + workDir + " status");
    } catch (error) {
      console.log(error.red);
      throw error;
    }
  },
  gitDir: function(workDir) {
    return workDir + '/.git';
  },
  clone: function(workDir, origin, branch, callback) {
    var error;
    error = null;
    return console.log('clone %s into %s and checkout %s', origin, workDir, branch);
  }
};
