// Generated by CoffeeScript 1.4.0
var colors, exec, shell;

exec = require('exec-sync');

colors = require('colors');

module.exports = shell = {
  execSync: function(command) {
    console.log('(run)'.bold, command);
    return exec(command);
  }
};
