// Generated by CoffeeScript 1.4.0
var colors, exec, fs, shell;

exec = require('exec-sync');

colors = require('colors');

fs = require('fs');

module.exports = shell = {
  gotDirectory: function(directory) {
    try {
      return fs.lstatSync(directory).isDirectory();
    } catch (error) {
      return false;
    }
  },
  makeDirectory: function(directory) {
    try {
      return exec("mkdir -p " + directory);
    } catch (error) {
      console.log(error.red);
      throw error;
    }
  },
  execSync: function(command) {
    console.log('(run)'.bold, command);
    return exec(command);
  }
};
