// Generated by CoffeeScript 1.4.0
var colors, exec, fs, shell, spawn;

exec = require('exec-sync');

spawn = require('child_process').spawn;

colors = require('colors');

fs = require('fs');

module.exports = shell = {
  gotDirectory: function(directory) {
    try {
      return fs.lstatSync(directory).isDirectory();
    } catch (error) {
      return false;
    }
  },
  makeDirectory: function(directory) {
    try {
      return exec("mkdir -p " + directory);
    } catch (error) {
      console.log(error.red);
      throw error;
    }
  },
  execSync: function(command, log) {
    if (log == null) {
      log = false;
    }
    if (log) {
      console.log('(run)'.bold, command);
    }
    return exec(command);
  },
  spawn: function(command, opts, callback) {
    var child;
    console.log('(run)'.bold, command, opts.join(' '));
    child = spawn(command, opts);
    child.stdout.pipe(process.stdout);
    child.stderr.pipe(process.stderr);
    return child.on('close', function(code, signal) {
      if (code > 0) {
        return callback(new Error(("'" + command + " " + (opts.join(' ')) + "'") + ' exited with errorcode: ' + code));
      } else {
        return callback(null);
      }
    });
  }
};
