// Generated by CoffeeScript 1.4.0
var sync;

module.exports = sync = {
  series: function(targetsArray, functionName, args, callback) {
    return console.log('%s on %s', functionName, targetsArray);
  }
};
